const STANDARD="https://abs.sirvisetti.com";
const capabilities=[
{id:"procurement.purchase-order.submit",title:"Submit Purchase Order",summary:"Submit a purchase order into its applicable business review, approval, or receiving flow.",definition:`${STANDARD}/domains/procurement/capabilities/purchase-order/submit.yaml`,inputSchema:`${STANDARD}/schemas/objects/procurement/purchase-order.schema.json`,effect:"approval → pending"},
{id:"finance.journal-entry.post",title:"Post Journal Entry",summary:"Post a balanced journal entry to the applicable accounting records.",definition:`${STANDARD}/domains/finance/capabilities/journal-entry/post.yaml`,inputSchema:`${STANDARD}/schemas/objects/finance/journal-entry.schema.json`,effect:"lifecycle → posted"},
{id:"hr.leave-request.submit",title:"Submit Leave Request",summary:"Submit a worker leave request for the applicable business review and approval.",definition:`${STANDARD}/domains/hr/capabilities/leave-request/submit.yaml`,inputSchema:`${STANDARD}/schemas/objects/hr/leave-request.schema.json`,effect:"lifecycle → submitted; approval → pending"}
];
function json(value:unknown,status=200){return new Response(JSON.stringify(value,null,2),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function missing(payload:any,fields:string[]){return fields.filter(f=>payload==null||payload[f]===undefined||payload[f]===null)}
function validate(id:string,p:any){if(id==="procurement.purchase-order.submit")return missing(p,["number","buyer","supplier","orderDate","currency","lines","status"]);if(id==="finance.journal-entry.post")return missing(p,["number","accountingDate","currency","lines","status"]);if(id==="hr.leave-request.submit")return missing(p,["number","worker","leaveType","startDate","endDate","status"]);return[]}
function apply(id:string,p:any){const out=structuredClone(p);if(id==="procurement.purchase-order.submit")out.status={...(out.status||{}),approval:"pending"};if(id==="finance.journal-entry.post")out.status={...(out.status||{}),lifecycle:"posted"};if(id==="hr.leave-request.submit")out.status={...(out.status||{}),lifecycle:"submitted",approval:"pending"};return out}
export default async (req:Request)=>{const url=new URL(req.url);if(req.method==="GET"){const id=url.searchParams.get("id");if(!id)return json({abcs:"0.2",reference:true,capabilities});const found=capabilities.find(c=>c.id===id);return found?json({abcs:"0.2",reference:true,...found}):json({abcs:"0.2",error:{code:"CAPABILITY_NOT_SUPPORTED",message:"Capability is not implemented by this reference surface."}},404)}if(req.method!=="POST")return json({error:{code:"METHOD_NOT_ALLOWED",message:"Use GET or POST."}},405);let body:any;try{body=await req.json()}catch{return json({abcs:"0.2",outcome:"rejected",errors:[{code:"INVALID_JSON",message:"Request body must be JSON."}]},400)}const {abcs,capability,requestId,payload}=body||{};if(abcs!=="0.2"||!capability||!requestId||payload===undefined)return json({abcs:"0.2",capability:capability||"unknown",requestId:requestId||"unknown",outcome:"rejected",errors:[{code:"INVALID_ENVELOPE",message:"abcs, capability, requestId and payload are required."}]},400);const found=capabilities.find(c=>c.id===capability);if(!found)return json({abcs:"0.2",capability,requestId,outcome:"rejected",errors:[{code:"CAPABILITY_NOT_SUPPORTED",message:"Capability is not implemented by this reference surface."}]},404);const absent=validate(capability,payload);if(absent.length)return json({abcs:"0.2",capability,requestId,outcome:"rejected",errors:[{code:"CANONICAL_PAYLOAD_INVALID",message:`Missing required canonical fields: ${absent.join(", ")}`,details:{schema:found.inputSchema}}]},422);return json({abcs:"0.2",capability,requestId,outcome:"completed",payload:apply(capability,payload),reference:{nonNormative:true,definition:found.definition,schema:found.inputSchema}})};